[package]
name = "voxel-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { version = "26.0.1" }
bytemuck = "1.23.2"
env_logger = "0.11.8"
pollster = "0.4.0"
winit = "0.30.12"
anyhow = "1.0.99"
cgmath = "0.18.0"
crossbeam-channel = "0.5.15"
image = { version = "0.25.5", default-features = false, features = ["png"] }
fastanvil = "0.32.0"
fastnbt = "2.6.0"
flate2 = "1.1.0"
serde = { version = "1.0.218", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4.55"
web-sys = { version = "0.3.82", features = ["Window", "Document", "HtmlCanvasElement"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1.10.0"
